name: Deploy FastAPI App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy FastAPI Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }} # Server IP address
          SSH_USER: ${{ secrets.SSH_USER }} # SSH username
          SSH_KEY: ${{ secrets.SSH_KEY }} # SSH private key
        run: |
          echo "$SSH_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem  # Set correct permissions for the key

          # Connect to the server and pull the latest code
          ssh -o StrictHostKeyChecking=no -i deploy_key.pem $SSH_USER@$SSH_HOST << EOF
            cd /path/to/your/fastapi/project  # Change to your deployment directory
            git pull origin main  # Pull latest changes
            source venv/bin/activate  # Activate virtual environment
            pip install -r requirements.txt  # Install new dependencies if any
            systemctl restart fastapi-app  # Restart FastAPI service
          EOF
